spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:devdb}
    username: ${PGUSER:ups}
    password: ${PGPASSWORD:ups123}
    hikari:
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (M√çNIMO 32 CARACTERES)
jwt:
  secret: ${PGJWTSECRET:EstaEsMiClaveSecretaSuperLargaParaJWT256Bits2024!!}
  expiration: 86400000
  header: "Authorization"
  prefix: "Bearer "

server:
  port: 8080

# ACTIVA TODOS LOS LOGS
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    ec.edu.ups.icc: TRACE
    jakarta.persistence: DEBUG